version: "3.3"

services:
  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./web/src:/app

  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./api/src:/app
  
  mysql:
    build:
      context: mysql
      dockerfile: Dockerfile
    restart: always
    command: --init-file /data/application/data.sql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '8002:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
